
name = "DashChakrauiComponents"
uuid = "1b08a953-4be3-4667-9a23-d8cb249726ec"
authors = ["José Luiz Ferreira <jlfsjunior@gmail.com>"]
version = "0.0.8"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
