name: Upload Documentation to Heroku

on:
  push:
    paths:
      - 'docs/**'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy docs to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.DOCS_HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "docs/"
