name: Tests

on:
  push: 
    branches: [ master, 'feat/**', 'feature/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    steps: 
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "10"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install python libraries
        run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Install node dependencies
        run: |
          npm install
      - name: Build package
        run: | 
          source venv/bin/activate && npm run build
  test-unit: 
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "10"
      - name: Instal node dependencies
        run: |
          npm install
      - name: Run Jest
        run: |
          npm run test:unit

  test-integration:
    runs-on: ubuntu-latest
    needs: test-unit
    steps: 
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Set up Selenium
        uses: nanasess/setup-chromedriver@v1.0.5
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('tests/requirements.txt') }}
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
      - name: Run tests
        run: pytest --headless
    
